# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# these stuffs need to be run before prezto
# env suggetions for conda 
fpath+=/home/minhduc0711/.conda-zsh-completion
# change ls dir colors
eval "$(dircolors ~/.dircolors)"

# prezto init
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# eliminate normal mode delay when using vi mode
export KEYTIMEOUT=1

# aliases
alias vim='nvim'
alias open='xdg-open'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/minhduc0711/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f "/home/minhduc0711/miniconda3/etc/profile.d/conda.sh" ]; then
    . "/home/minhduc0711/miniconda3/etc/profile.d/conda.sh"
  else
    export PATH="/home/minhduc0711/miniconda3/bin:$PATH"
  fi
fi
unset __conda_setup
# <<< conda initialize <<<

# conda auto activating env when in project dir
if [[ -e ~/.autoenv ]]; then
  export AUTOENV_ENABLE_LEAVE=true
  export AUTOENV_ASSUME_YES=true
  source ~/.autoenv/activate.sh
fi

# NodeJS
export NODEJS_HOME=/opt/node-v12.18.3-linux-x64/bin
export PATH=$NODEJS_HOME:$PATH

# access jupyter lab instance on remote server
function jllocal {
  remote_username=ducpm
  remote_hostname=ictlab.usth.edu.vn
  # open urls on browser after forwarding
  (sleep 2; 
  for p in "$@"; do
    url="http://localhost:${p}"
    echo "opening $url"
    #xdg-open $url
  done) &
  # Forward ports 
  forward_args=""
  for p in "$@"; do
    forward_args="${forward_args}-L localhost:${p}:localhost:${p} "
  done
  ssh_cmd="ssh -p 22222 -CN $remote_username@$remote_hostname $forward_args"
  echo $ssh_cmd
  eval $ssh_cmd
}

# use fd instead of find for fzf
alias fd=fdfind
export FZF_DEFAULT_COMMAND='fdfind --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# add fzf key bindings, this must go after prezto init
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey '^P' fzf-file-widget
bindkey '^T' transpose-chars

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
