# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# these stuffs need to be run before prezto
# env suggetions for conda 
fpath+=/home/minhduc0711/.conda-zsh-completion
# change ls dir colors
export TERM=xterm-256color
eval "$(dircolors ~/.dircolors)"

# prezto init
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# eliminate normal mode delay when using vi mode
export KEYTIMEOUT=1

# aliases
alias vim='nvim'
alias open='xdg-open'
alias git-delete-squashed='git checkout -q master && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base master $branch) && [[ $(git cherry master $(git commit-tree $(git rev-parse $branch\^{tree}) -p $mergeBase -m _)) == "-"* ]] && git branch -D $branch; done'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/minhduc0711/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f "/home/minhduc0711/miniconda3/etc/profile.d/conda.sh" ]; then
    . "/home/minhduc0711/miniconda3/etc/profile.d/conda.sh"
  else
    export PATH="/home/minhduc0711/miniconda3/bin:$PATH"
  fi
fi
unset __conda_setup
# <<< conda initialize <<<

# conda auto activating env when in project dir
if [[ -e ~/.autoenv/activate.sh ]]; then
  export AUTOENV_ENABLE_LEAVE=1
  export AUTOENV_ASSUME_YES=1
  source ~/.autoenv/activate.sh
fi

# access jupyter lab instance on remote server
function jllocal {
  host=$1
  shift
  # open urls on browser after forwarding
  (sleep 2; 
  for p in "$@"; do
    url="http://localhost:${p}"
    echo "opening $url"
    xdg-open $url
  done) &
  # Forward ports 
  forward_args=""
  for p in "$@"; do
    forward_args="${forward_args} -L localhost:${p}:localhost:${p}"
  done
  ssh_cmd="ssh -CN $host $forward_args"
  echo $ssh_cmd
  eval $ssh_cmd
}

# use fd instead of find for fzf
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# add fzf key bindings, this must go after prezto init
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
bindkey '^P' fzf-file-widget
bindkey '^T' transpose-chars

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
